/* Automatically generated by gen_ccy_data.py */
import { Locale, LocaleData } from '../../locale';

// Unicode CLDR Version 37
const data: LocaleData = {
  d: '.',
  g: ',',
};

export default new Locale('en', data);
