/* eslint-disable camelcase, unicorn/prevent-abbreviations */
/* Automatically generated by gen_l10n_data.py */
import { Locale } from '../locale';
import root from './root';

// Unicode CLDR Version 37, retrieved 2020-10-12
export const ar = new Locale(
  'ar',
  {
    p: '‎+',
    m: '‎-',
    pc: '‎%‎',
    nan: 'ليس رقمًا',
    cs: {
      AED: 'د.إ.‏',
      AUD: 'AU$',
      BHD: 'د.ب.‏',
      DZD: 'د.ج.‏',
      EGP: 'ج.م.‏',
      GBP: 'UK£',
      IQD: 'د.ع.‏',
      IRR: 'ر.إ.',
      JOD: 'د.أ.‏',
      KWD: 'د.ك.‏',
      LBP: 'ل.ل.‏',
      LYD: 'د.ل.‏',
      MAD: 'د.م.‏',
      MRU: 'أ.م.',
      OMR: 'ر.ع.‏',
      QAR: 'ر.ق.‏',
      SAR: 'ر.س.‏',
      SDG: 'ج.س.',
      SYP: 'ل.س.‏',
      THB: '฿',
      TND: 'د.ت.‏',
      XXX: '***',
      YER: 'ر.ي.‏',
    },
    cn: {
      AED: 'درهم إماراتي',
      AFN: 'أفغاني',
      ALL: 'ليك ألباني',
      AMD: 'درام أرميني',
      ANG: 'غيلدر أنتيلي هولندي',
      AOA: 'كوانزا أنغولي',
      ARS: 'بيزو أرجنتيني',
      AUD: 'دولار أسترالي',
      AWG: 'فلورن أروبي',
      AZN: 'مانات أذربيجان',
      BAM: 'مارك البوسنة والهرسك قابل للتحويل',
      BBD: 'دولار بربادوسي',
      BDT: 'تاكا بنغلاديشي',
      BGN: 'ليف بلغاري',
      BHD: 'دينار بحريني',
      BIF: 'فرنك بروندي',
      BMD: 'دولار برمودي',
      BND: 'دولار بروناي',
      BOB: 'بوليفيانو بوليفي',
      BRL: 'ريال برازيلي',
      BSD: 'دولار باهامي',
      BTN: 'نولتوم بوتاني',
      BWP: 'بولا بتسواني',
      BYN: 'روبل بيلاروسي',
      BZD: 'دولار بليزي',
      CAD: 'دولار كندي',
      CDF: 'فرنك كونغولي',
      CHF: 'فرنك سويسري',
      CLP: 'بيزو تشيلي',
      CNY: 'يوان صيني',
      COP: 'بيزو كولومبي',
      CRC: 'كولن كوستاريكي',
      CUC: 'بيزو كوبي قابل للتحويل',
      CUP: 'بيزو كوبي',
      CVE: 'اسكودو الرأس الأخضر',
      CZK: 'كرونة تشيكية',
      DJF: 'فرنك جيبوتي',
      DKK: 'كرونة دنماركية',
      DOP: 'بيزو الدومنيكان',
      DZD: 'دينار جزائري',
      EGP: 'جنيه مصري',
      ERN: 'ناكفا أريتري',
      ETB: 'بير أثيوبي',
      EUR: 'يورو',
      FJD: 'دولار فيجي',
      FKP: 'جنيه جزر فوكلاند',
      GBP: 'جنيه إسترليني',
      GEL: 'لارى جورجي',
      GHS: 'سيدي غانا',
      GIP: 'جنيه جبل طارق',
      GMD: 'دلاسي غامبي',
      GNF: 'فرنك غينيا',
      GTQ: 'كوتزال غواتيمالا',
      GYD: 'دولار غيانا',
      HKD: 'دولار هونغ كونغ',
      HNL: 'ليمبيرا هنداروس',
      HRK: 'كونا كرواتي',
      HTG: 'جوردى هايتي',
      HUF: 'فورينت هنغاري',
      IDR: 'روبية إندونيسية',
      ILS: 'شيكل إسرائيلي جديد',
      INR: 'روبية هندي',
      IQD: 'دينار عراقي',
      IRR: 'ريال إيراني',
      ISK: 'كرونة أيسلندية',
      JMD: 'دولار جامايكي',
      JOD: 'دينار أردني',
      JPY: 'ين ياباني',
      KES: 'شلن كينيي',
      KGS: 'سوم قيرغستاني',
      KHR: 'رييال كمبودي',
      KMF: 'فرنك جزر القمر',
      KPW: 'وون كوريا الشمالية',
      KRW: 'وون كوريا الجنوبية',
      KWD: 'دينار كويتي',
      KYD: 'دولار جزر كيمن',
      KZT: 'تينغ كازاخستاني',
      LAK: 'كيب لاوسي',
      LBP: 'جنيه لبناني',
      LKR: 'روبية سريلانكية',
      LRD: 'دولار ليبيري',
      LSL: 'لوتي ليسوتو',
      LYD: 'دينار ليبي',
      MAD: 'درهم مغربي',
      MDL: 'ليو مولدوفي',
      MGA: 'أرياري مدغشقر',
      MKD: 'دينار مقدوني',
      MMK: 'كيات ميانمار',
      MNT: 'توغروغ منغولي',
      MOP: 'باتاكا ماكاوي',
      MRU: 'أوقية موريتانية',
      MUR: 'روبية موريشيوسية',
      MVR: 'روفيه جزر المالديف',
      MWK: 'كواشا مالاوي',
      MXN: 'بيزو مكسيكي',
      MYR: 'رينغيت ماليزي',
      MZN: 'متكال موزمبيقي',
      NAD: 'دولار ناميبي',
      NGN: 'نايرا نيجيري',
      NIO: 'قرطبة نيكاراغوا',
      NOK: 'كرونة نرويجية',
      NPR: 'روبية نيبالي',
      NZD: 'دولار نيوزيلندي',
      OMR: 'ريال عماني',
      PAB: 'بالبوا بنمي',
      PEN: 'سول بيروفي',
      PGK: 'كينا بابوا غينيا الجديدة',
      PHP: 'بيزو فلبيني',
      PKR: 'روبية باكستاني',
      PLN: 'زلوتي بولندي',
      PYG: 'غواراني باراغواي',
      QAR: 'ريال قطري',
      RON: 'ليو روماني',
      RSD: 'دينار صربي',
      RUB: 'روبل روسي',
      RWF: 'فرنك رواندي',
      SAR: 'ريال سعودي',
      SBD: 'دولار جزر سليمان',
      SCR: 'روبية سيشيلية',
      SDG: 'جنيه سوداني',
      SEK: 'كرونة سويدية',
      SGD: 'دولار سنغافوري',
      SHP: 'جنيه سانت هيلين',
      SLL: 'ليون سيراليوني',
      SOS: 'شلن صومالي',
      SRD: 'دولار سورينامي',
      STN: 'دوبرا ساو تومي وبرينسيبي',
      SVC: 'كولون سلفادوري',
      SYP: 'ليرة سورية',
      SZL: 'ليلانجيني سوازيلندي',
      THB: 'باخت تايلاندي',
      TJS: 'سوموني طاجيكستاني',
      TMT: 'مانات تركمانستان',
      TND: 'دينار تونسي',
      TOP: 'بانغا تونغا',
      TRY: 'ليرة تركية',
      TTD: 'دولار ترينداد وتوباغو',
      TWD: 'دولار تايواني',
      TZS: 'شلن تنزاني',
      UAH: 'هريفنيا أوكراني',
      UGX: 'شلن أوغندي',
      USD: 'دولار أمريكي',
      UYU: 'بيزو اوروغواي',
      UZS: 'سوم أوزبكستاني',
      VND: 'دونج فيتنامي',
      VUV: 'فاتو فانواتو',
      WST: 'تالا ساموا',
      XAF: 'فرنك وسط أفريقي',
      XCD: 'دولار شرق الكاريبي',
      XDR: 'حقوق السحب الخاصة',
      XOF: 'فرنك غرب أفريقي',
      XPF: 'فرنك سي إف بي',
      XXX: 'عملة غير معروفة',
      YER: 'ريال يمني',
      ZAR: 'راند جنوب أفريقيا',
      ZMW: 'كواشا زامبي',
    },
    ap: '¤#,##0.00;(¤#,##0.00)',
  },
  root
);

// Locale Data
export const ar_AE = new Locale('ar_AE', { c: 'AED', cs: {}, cn: {} }, ar);
export const ar_BH = new Locale('ar_BH', { c: 'BHD', cs: {}, cn: {} }, ar);
export const ar_DJ = new Locale(
  'ar_DJ',
  { c: 'DJF', cs: { DJF: 'Fdj' }, cn: {} },
  ar
);
export const ar_DZ = new Locale(
  'ar_DZ',
  { d: ',', g: '.', c: 'DZD', cs: {}, cn: {} },
  ar
);
export const ar_EG = new Locale('ar_EG', { c: 'EGP', cs: {}, cn: {} }, ar);
export const ar_EH = new Locale('ar_EH', { c: 'MAD', cs: {}, cn: {} }, ar);
export const ar_ER = new Locale(
  'ar_ER',
  { c: 'ERN', cs: { ERN: 'Nfk' }, cn: {} },
  ar
);
export const ar_IL = new Locale('ar_IL', { c: 'ILS', cs: {}, cn: {} }, ar);
export const ar_IQ = new Locale('ar_IQ', { c: 'IQD', cs: {}, cn: {} }, ar);
export const ar_JO = new Locale('ar_JO', { c: 'JOD', cs: {}, cn: {} }, ar);
export const ar_KM = new Locale(
  'ar_KM',
  { c: 'KMF', cs: { KMF: 'CF' }, cn: {} },
  ar
);
export const ar_KW = new Locale('ar_KW', { c: 'KWD', cs: {}, cn: {} }, ar);
export const ar_LB = new Locale(
  'ar_LB',
  { d: ',', g: '.', c: 'LBP', cs: {}, cn: {} },
  ar
);
export const ar_LY = new Locale(
  'ar_LY',
  { d: ',', g: '.', c: 'LYD', cs: {}, cn: {} },
  ar
);
export const ar_MA = new Locale(
  'ar_MA',
  { d: ',', g: '.', c: 'MAD', cs: {}, cn: {} },
  ar
);
export const ar_MR = new Locale(
  'ar_MR',
  { d: ',', g: '.', c: 'MRU', cs: {}, cn: {} },
  ar
);
export const ar_OM = new Locale('ar_OM', { c: 'OMR', cs: {}, cn: {} }, ar);
export const ar_PS = new Locale('ar_PS', { c: 'JOD', cs: {}, cn: {} }, ar);
export const ar_QA = new Locale('ar_QA', { c: 'QAR', cs: {}, cn: {} }, ar);
export const ar_SA = new Locale(
  'ar_SA',
  { pc: '٪', c: 'SAR', cs: {}, cn: {} },
  ar
);
export const ar_SD = new Locale('ar_SD', { c: 'SDG', cs: {}, cn: {} }, ar);
export const ar_SO = new Locale(
  'ar_SO',
  { pc: '٪', c: 'SOS', cs: { SOS: 'S' }, cn: {} },
  ar
);
export const ar_SS = new Locale(
  'ar_SS',
  { c: 'SSP', cs: { GBP: 'GB£' }, cn: {} },
  ar
);
export const ar_SY = new Locale('ar_SY', { c: 'SYP', cs: {}, cn: {} }, ar);
export const ar_TD = new Locale('ar_TD', { c: 'XAF', cs: {}, cn: {} }, ar);
export const ar_TN = new Locale(
  'ar_TN',
  { d: ',', g: '.', c: 'TND', cs: {}, cn: {} },
  ar
);
export const ar_YE = new Locale('ar_YE', { c: 'YER', cs: {}, cn: {} }, ar);

// Default Export
export default ar;
