/* eslint-disable camelcase, unicorn/prevent-abbreviations */
/**
 * Automatically generated by gen_l10n_data.py
 * @packageDocumentation
 * @internal
 */
import { Locale } from '../locale';
import root from './root';

// Unicode CLDR Version 37, retrieved 2020-10-23
export const en = new Locale(
  'en',
  {
    cs: { JPY: '¥', USD: '$' },
    cn: {
      AED: 'United Arab Emirates Dirham',
      AFN: 'Afghan Afghani',
      ALL: 'Albanian Lek',
      AMD: 'Armenian Dram',
      ANG: 'Netherlands Antillean Guilder',
      AOA: 'Angolan Kwanza',
      ARS: 'Argentine Peso',
      AUD: 'Australian Dollar',
      AWG: 'Aruban Florin',
      AZN: 'Azerbaijani Manat',
      BAM: 'Bosnia-Herzegovina Convertible Mark',
      BBD: 'Barbadian Dollar',
      BDT: 'Bangladeshi Taka',
      BGN: 'Bulgarian Lev',
      BHD: 'Bahraini Dinar',
      BIF: 'Burundian Franc',
      BMD: 'Bermudan Dollar',
      BND: 'Brunei Dollar',
      BOB: 'Bolivian Boliviano',
      BRL: 'Brazilian Real',
      BSD: 'Bahamian Dollar',
      BTN: 'Bhutanese Ngultrum',
      BWP: 'Botswanan Pula',
      BYN: 'Belarusian Ruble',
      BZD: 'Belize Dollar',
      CAD: 'Canadian Dollar',
      CDF: 'Congolese Franc',
      CHF: 'Swiss Franc',
      CLP: 'Chilean Peso',
      CNY: 'Chinese Yuan',
      COP: 'Colombian Peso',
      CRC: 'Costa Rican Colón',
      CUC: 'Cuban Convertible Peso',
      CUP: 'Cuban Peso',
      CVE: 'Cape Verdean Escudo',
      CZK: 'Czech Koruna',
      DJF: 'Djiboutian Franc',
      DKK: 'Danish Krone',
      DOP: 'Dominican Peso',
      DZD: 'Algerian Dinar',
      EGP: 'Egyptian Pound',
      ERN: 'Eritrean Nakfa',
      ETB: 'Ethiopian Birr',
      EUR: 'Euro',
      FJD: 'Fijian Dollar',
      FKP: 'Falkland Islands Pound',
      GBP: 'British Pound',
      GEL: 'Georgian Lari',
      GHS: 'Ghanaian Cedi',
      GIP: 'Gibraltar Pound',
      GMD: 'Gambian Dalasi',
      GNF: 'Guinean Franc',
      GTQ: 'Guatemalan Quetzal',
      GYD: 'Guyanaese Dollar',
      HKD: 'Hong Kong Dollar',
      HNL: 'Honduran Lempira',
      HRK: 'Croatian Kuna',
      HTG: 'Haitian Gourde',
      HUF: 'Hungarian Forint',
      IDR: 'Indonesian Rupiah',
      ILS: 'Israeli New Shekel',
      INR: 'Indian Rupee',
      IQD: 'Iraqi Dinar',
      IRR: 'Iranian Rial',
      ISK: 'Icelandic Króna',
      JMD: 'Jamaican Dollar',
      JOD: 'Jordanian Dinar',
      JPY: 'Japanese Yen',
      KES: 'Kenyan Shilling',
      KGS: 'Kyrgystani Som',
      KHR: 'Cambodian Riel',
      KMF: 'Comorian Franc',
      KPW: 'North Korean Won',
      KRW: 'South Korean Won',
      KWD: 'Kuwaiti Dinar',
      KYD: 'Cayman Islands Dollar',
      KZT: 'Kazakhstani Tenge',
      LAK: 'Laotian Kip',
      LBP: 'Lebanese Pound',
      LKR: 'Sri Lankan Rupee',
      LRD: 'Liberian Dollar',
      LSL: 'Lesotho Loti',
      LYD: 'Libyan Dinar',
      MAD: 'Moroccan Dirham',
      MDL: 'Moldovan Leu',
      MGA: 'Malagasy Ariary',
      MKD: 'Macedonian Denar',
      MMK: 'Myanmar Kyat',
      MNT: 'Mongolian Tugrik',
      MOP: 'Macanese Pataca',
      MRU: 'Mauritanian Ouguiya',
      MUR: 'Mauritian Rupee',
      MVR: 'Maldivian Rufiyaa',
      MWK: 'Malawian Kwacha',
      MXN: 'Mexican Peso',
      MYR: 'Malaysian Ringgit',
      MZN: 'Mozambican Metical',
      NAD: 'Namibian Dollar',
      NGN: 'Nigerian Naira',
      NIO: 'Nicaraguan Córdoba',
      NOK: 'Norwegian Krone',
      NPR: 'Nepalese Rupee',
      NZD: 'New Zealand Dollar',
      OMR: 'Omani Rial',
      PAB: 'Panamanian Balboa',
      PEN: 'Peruvian Sol',
      PGK: 'Papua New Guinean Kina',
      PHP: 'Philippine Piso',
      PKR: 'Pakistani Rupee',
      PLN: 'Polish Zloty',
      PYG: 'Paraguayan Guarani',
      QAR: 'Qatari Rial',
      RON: 'Romanian Leu',
      RSD: 'Serbian Dinar',
      RUB: 'Russian Ruble',
      RWF: 'Rwandan Franc',
      SAR: 'Saudi Riyal',
      SBD: 'Solomon Islands Dollar',
      SCR: 'Seychellois Rupee',
      SDG: 'Sudanese Pound',
      SEK: 'Swedish Krona',
      SGD: 'Singapore Dollar',
      SHP: 'St. Helena Pound',
      SLL: 'Sierra Leonean Leone',
      SOS: 'Somali Shilling',
      SRD: 'Surinamese Dollar',
      STN: 'São Tomé & Príncipe Dobra',
      SVC: 'Salvadoran Colón',
      SYP: 'Syrian Pound',
      SZL: 'Swazi Lilangeni',
      THB: 'Thai Baht',
      TJS: 'Tajikistani Somoni',
      TMT: 'Turkmenistani Manat',
      TND: 'Tunisian Dinar',
      TOP: 'Tongan Paʻanga',
      TRY: 'Turkish Lira',
      TTD: 'Trinidad & Tobago Dollar',
      TWD: 'New Taiwan Dollar',
      TZS: 'Tanzanian Shilling',
      UAH: 'Ukrainian Hryvnia',
      UGX: 'Ugandan Shilling',
      USD: 'US Dollar',
      UYU: 'Uruguayan Peso',
      UZS: 'Uzbekistani Som',
      VND: 'Vietnamese Dong',
      VUV: 'Vanuatu Vatu',
      WST: 'Samoan Tala',
      XAF: 'Central African CFA Franc',
      XCD: 'East Caribbean Dollar',
      XDR: 'Special Drawing Rights',
      XOF: 'West African CFA Franc',
      XPF: 'CFP Franc',
      XXX: 'Unknown Currency',
      YER: 'Yemeni Rial',
      ZAR: 'South African Rand',
      ZMW: 'Zambian Kwacha',
    },
    cp: '¤#,##0.00',
    ap: '¤#,##0.00;(¤#,##0.00)',
  },
  root
);

// Common Locale Parents
export const en_001 = new Locale(
  'en_001',
  {
    cs: {},
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },
  en
);

export const en_150 = new Locale(
  'en_150',
  {
    cs: {},
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
    cp: '#,##0.00 ¤',
    ap: '#,##0.00 ¤',
  },
  en
);

// Locale Data
export const en_AE = new Locale('en_AE', { c: 'AED', cs: {}, cn: {} }, en);
export const en_AG = new Locale(
  'en_AG',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_AI = new Locale(
  'en_AI',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_AS = new Locale('en_AS', { c: 'USD', cs: {}, cn: {} }, en);
export const en_AT = new Locale(
  'en_AT',
  { d: ',', g: '.', x: '·', c: 'EUR', cs: {}, cn: {}, pp: '#,##0 %' },
  en_150
);
export const en_AU = new Locale(
  'en_AU',
  {
    e: 'e',
    c: 'AUD',
    cs: { AUD: '$', SCR: 'Rs', XPF: 'CFP' },
    cn: {
      BAM: 'Bosnia-Herzegovina Convertible Marka',
      BBD: 'Barbados Dollar',
      BMD: 'Bermuda Dollar',
      BOB: 'Boliviano',
      ILS: 'Israeli Shekel',
      QAR: 'Qatari Riyal',
      SRD: 'Suriname Dollar',
      UYU: 'Peso Uruguayo',
    },
  },
  en_001
);
export const en_BB = new Locale(
  'en_BB',
  { c: 'BBD', cs: { BBD: '$' }, cn: {} },
  en_001
);
export const en_BE = new Locale(
  'en_BE',
  { d: ',', g: '.', c: 'EUR', cs: {}, cn: {} },
  en_150
);
export const en_BI = new Locale(
  'en_BI',
  { c: 'BIF', cs: { BIF: 'FBu' }, cn: {} },
  en
);
export const en_BM = new Locale(
  'en_BM',
  { c: 'BMD', cs: { BMD: '$' }, cn: {} },
  en_001
);
export const en_BS = new Locale(
  'en_BS',
  { c: 'BSD', cs: { BSD: '$' }, cn: {} },
  en_001
);
export const en_BW = new Locale(
  'en_BW',
  { c: 'BWP', cs: { BWP: 'P' }, cn: {} },
  en_001
);
export const en_BZ = new Locale(
  'en_BZ',
  { c: 'BZD', cs: { BZD: '$' }, cn: {} },
  en_001
);
export const en_CA = new Locale(
  'en_CA',
  { e: 'e', c: 'CAD', cs: { CAD: '$' }, cn: {} },
  en_001
);
export const en_CC = new Locale(
  'en_CC',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_CH = new Locale(
  'en_CH',
  {
    g: '’',
    x: '·',
    c: 'CHF',
    cs: {},
    cn: {},
    cp: '¤ #,##0.00;¤-#,##0.00',
    ap: '¤ #,##0.00;¤-#,##0.00',
  },
  en_150
);
export const en_CK = new Locale(
  'en_CK',
  { c: 'NZD', cs: { NZD: '$' }, cn: {} },
  en_001
);
export const en_CM = new Locale('en_CM', { c: 'XAF', cs: {}, cn: {} }, en_001);
export const en_CX = new Locale(
  'en_CX',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_CY = new Locale('en_CY', { c: 'EUR', cs: {}, cn: {} }, en_001);
export const en_DE = new Locale(
  'en_DE',
  { d: ',', g: '.', x: '·', c: 'EUR', cs: {}, cn: {}, pp: '#,##0 %' },
  en_150
);
export const en_DG = new Locale('en_DG', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_DK = new Locale(
  'en_DK',
  {
    d: ',',
    g: '.',
    x: '·',
    c: 'DKK',
    cs: { DKK: 'kr.' },
    cn: {},
    pp: '#,##0 %',
  },
  en_150
);
export const en_DM = new Locale(
  'en_DM',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_ER = new Locale(
  'en_ER',
  { c: 'ERN', cs: { ERN: 'Nfk' }, cn: {} },
  en_001
);
export const en_FI = new Locale(
  'en_FI',
  { d: ',', g: ' ', c: 'EUR', cs: {}, cn: {}, pp: '#,##0 %' },
  en_150
);
export const en_FJ = new Locale(
  'en_FJ',
  { c: 'FJD', cs: { FJD: '$' }, cn: {} },
  en_001
);
export const en_FK = new Locale(
  'en_FK',
  { c: 'FKP', cs: { FKP: '£', GBP: 'GB£' }, cn: {} },
  en_001
);
export const en_FM = new Locale('en_FM', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_GB = new Locale('en_GB', { c: 'GBP', cs: {}, cn: {} }, en_001);
export const en_GD = new Locale(
  'en_GD',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_GG = new Locale(
  'en_GG',
  { c: 'GBP', cs: {}, cn: { GBP: 'UK Pound' } },
  en_001
);
export const en_GH = new Locale(
  'en_GH',
  { c: 'GHS', cs: { GHS: 'GH₵' }, cn: {} },
  en_001
);
export const en_GI = new Locale(
  'en_GI',
  { c: 'GIP', cs: { GBP: 'GB£', GIP: '£' }, cn: {} },
  en_001
);
export const en_GM = new Locale(
  'en_GM',
  { c: 'GMD', cs: { GMD: 'D' }, cn: {} },
  en_001
);
export const en_GU = new Locale('en_GU', { c: 'USD', cs: {}, cn: {} }, en);
export const en_GY = new Locale(
  'en_GY',
  { c: 'GYD', cs: { GYD: '$' }, cn: {} },
  en_001
);
export const en_HK = new Locale('en_HK', { c: 'HKD', cs: {}, cn: {} }, en_001);
export const en_IE = new Locale('en_IE', { c: 'EUR', cs: {}, cn: {} }, en_001);
export const en_IL = new Locale('en_IL', { c: 'ILS', cs: {}, cn: {} }, en_001);
export const en_IM = new Locale(
  'en_IM',
  { c: 'GBP', cs: {}, cn: { GBP: 'UK Pound' } },
  en_001
);
export const en_IN = new Locale(
  'en_IN',
  {
    c: 'INR',
    cs: {},
    cn: {},
    np: '#,##,##0.###',
    pp: '#,##,##0%',
    cp: '¤#,##,##0.00',
  },
  en_001
);
export const en_IO = new Locale('en_IO', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_JE = new Locale(
  'en_JE',
  { c: 'GBP', cs: {}, cn: { GBP: 'UK Pound' } },
  en_001
);
export const en_JM = new Locale(
  'en_JM',
  { c: 'JMD', cs: { JMD: '$' }, cn: {} },
  en_001
);
export const en_KE = new Locale(
  'en_KE',
  { c: 'KES', cs: { KES: 'Ksh' }, cn: {} },
  en_001
);
export const en_KI = new Locale(
  'en_KI',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_KN = new Locale(
  'en_KN',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_KY = new Locale(
  'en_KY',
  { c: 'KYD', cs: { KYD: '$' }, cn: {} },
  en_001
);
export const en_LC = new Locale(
  'en_LC',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_LR = new Locale(
  'en_LR',
  { c: 'LRD', cs: { LRD: '$' }, cn: {} },
  en_001
);
export const en_LS = new Locale(
  'en_LS',
  { c: 'LSL', cs: { ZAR: 'R' }, cn: {} },
  en_001
);
export const en_MG = new Locale(
  'en_MG',
  { c: 'MGA', cs: { MGA: 'Ar' }, cn: {} },
  en_001
);
export const en_MH = new Locale('en_MH', { c: 'USD', cs: {}, cn: {} }, en);
export const en_MO = new Locale(
  'en_MO',
  { c: 'MOP', cs: { MOP: 'MOP$' }, cn: {} },
  en_001
);
export const en_MP = new Locale('en_MP', { c: 'USD', cs: {}, cn: {} }, en);
export const en_MS = new Locale(
  'en_MS',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_MT = new Locale(
  'en_MT',
  { c: 'EUR', cs: { GBP: 'GB£' }, cn: {} },
  en_001
);
export const en_MU = new Locale(
  'en_MU',
  { c: 'MUR', cs: { MUR: 'Rs' }, cn: {} },
  en_001
);
export const en_MW = new Locale(
  'en_MW',
  { c: 'MWK', cs: { MWK: 'MK' }, cn: {} },
  en_001
);
export const en_MY = new Locale(
  'en_MY',
  { c: 'MYR', cs: { MYR: 'RM' }, cn: {} },
  en_001
);
export const en_NA = new Locale(
  'en_NA',
  { c: 'NAD', cs: { NAD: '$' }, cn: {} },
  en_001
);
export const en_NF = new Locale(
  'en_NF',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_NG = new Locale(
  'en_NG',
  { c: 'NGN', cs: { NGN: '₦' }, cn: {} },
  en_001
);
export const en_NL = new Locale(
  'en_NL',
  {
    d: ',',
    g: '.',
    c: 'EUR',
    cs: {},
    cn: {},
    cp: '¤ #,##0.00;¤ -#,##0.00',
    ap: '¤ #,##0.00;(¤ #,##0.00)',
  },
  en_150
);
export const en_NR = new Locale(
  'en_NR',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_NU = new Locale(
  'en_NU',
  { c: 'NZD', cs: { NZD: '$' }, cn: {} },
  en_001
);
export const en_NZ = new Locale(
  'en_NZ',
  { c: 'NZD', cs: { NZD: '$' }, cn: {} },
  en_001
);
export const en_PG = new Locale(
  'en_PG',
  { c: 'PGK', cs: { PGK: 'K' }, cn: {} },
  en_001
);
export const en_PH = new Locale(
  'en_PH',
  { c: 'PHP', cs: { PHP: '₱' }, cn: {} },
  en_001
);
export const en_PK = new Locale(
  'en_PK',
  { c: 'PKR', cs: { PKR: 'Rs' }, cn: {} },
  en_001
);
export const en_PN = new Locale(
  'en_PN',
  { c: 'NZD', cs: { NZD: '$' }, cn: {} },
  en_001
);
export const en_PR = new Locale('en_PR', { c: 'USD', cs: {}, cn: {} }, en);
export const en_PW = new Locale('en_PW', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_RW = new Locale(
  'en_RW',
  { c: 'RWF', cs: { RWF: 'RF' }, cn: {} },
  en_001
);
export const en_SB = new Locale(
  'en_SB',
  { c: 'SBD', cs: { SBD: '$' }, cn: {} },
  en_001
);
export const en_SC = new Locale(
  'en_SC',
  { c: 'SCR', cs: { SCR: 'SR' }, cn: {} },
  en_001
);
export const en_SD = new Locale('en_SD', { c: 'SDG', cs: {}, cn: {} }, en_001);
export const en_SE = new Locale(
  'en_SE',
  {
    d: ',',
    g: ' ',
    e: '×10^',
    c: 'SEK',
    cs: { SEK: 'kr' },
    cn: {},
    pp: '#,##0 %',
  },
  en_150
);
export const en_SG = new Locale(
  'en_SG',
  { c: 'SGD', cs: { SGD: '$' }, cn: {} },
  en_001
);
export const en_SH = new Locale(
  'en_SH',
  { c: 'SHP', cs: { GBP: 'GB£', SHP: '£' }, cn: {} },
  en_001
);
export const en_SI = new Locale(
  'en_SI',
  {
    d: ',',
    g: '.',
    e: 'e',
    c: 'EUR',
    cs: {},
    cn: {},
    ap: '#,##0.00 ¤;(#,##0.00 ¤)',
  },
  en_150
);
export const en_SL = new Locale(
  'en_SL',
  { c: 'SLL', cs: { SLL: 'Le' }, cn: {} },
  en_001
);
export const en_SS = new Locale(
  'en_SS',
  { c: 'SSP', cs: { GBP: 'GB£' }, cn: {} },
  en_001
);
export const en_SX = new Locale(
  'en_SX',
  { c: 'ANG', cs: { ANG: 'NAf.' }, cn: {} },
  en_001
);
export const en_SZ = new Locale(
  'en_SZ',
  { c: 'SZL', cs: { SZL: 'E' }, cn: {} },
  en_001
);
export const en_TC = new Locale('en_TC', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_TK = new Locale(
  'en_TK',
  { c: 'NZD', cs: { NZD: '$' }, cn: {} },
  en_001
);
export const en_TO = new Locale(
  'en_TO',
  { c: 'TOP', cs: { TOP: 'T$' }, cn: {} },
  en_001
);
export const en_TT = new Locale(
  'en_TT',
  { c: 'TTD', cs: { TTD: '$' }, cn: {} },
  en_001
);
export const en_TV = new Locale(
  'en_TV',
  { c: 'AUD', cs: { AUD: '$' }, cn: {} },
  en_001
);
export const en_TZ = new Locale(
  'en_TZ',
  { c: 'TZS', cs: { TZS: 'TSh' }, cn: {} },
  en_001
);
export const en_UG = new Locale(
  'en_UG',
  { c: 'UGX', cs: { UGX: 'USh' }, cn: {} },
  en_001
);
export const en_UM = new Locale('en_UM', { c: 'USD', cs: {}, cn: {} }, en);
export const en_US_POSIX = new Locale(
  'en_US_POSIX',
  {
    pm: '0/00',
    inf: 'INF',
    c: 'USD',
    cs: {},
    cn: {},
    np: '0.######',
    pp: '0%',
    sp: '0.000000E+000',
    cp: '¤ 0.00',
  },
  en
);
export const en_VC = new Locale(
  'en_VC',
  { c: 'XCD', cs: { XCD: '$' }, cn: {} },
  en_001
);
export const en_VG = new Locale('en_VG', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_VI = new Locale('en_VI', { c: 'USD', cs: {}, cn: {} }, en);
export const en_VU = new Locale(
  'en_VU',
  { c: 'VUV', cs: { VUV: 'VT' }, cn: {} },
  en_001
);
export const en_WS = new Locale(
  'en_WS',
  { c: 'WST', cs: { WST: 'WS$' }, cn: {} },
  en_001
);
export const en_ZA = new Locale(
  'en_ZA',
  { d: ',', g: ' ', c: 'ZAR', cs: { ZAR: 'R' }, cn: {} },
  en_001
);
export const en_ZM = new Locale(
  'en_ZM',
  { c: 'ZMW', cs: { ZMW: 'K' }, cn: {} },
  en_001
);
export const en_ZW = new Locale('en_ZW', { c: 'USD', cs: {}, cn: {} }, en_001);
export const en_US = new Locale('en_US', { c: 'USD' }, en);

// Default Export
export default en;
