/* Automatically generated by gen_l10n_data.py */
import { Locale } from '../locale';
import root from '../root';

// Unicode CLDR Version 37, retrieved 2020-10-11
export const es = new Locale(
  'es',
  {
    d: ',',
    g: '.',
    cs: { THB: '฿' },
    cn: {
      AED: 'dírham de los Emiratos Árabes Unidos',
      AFN: 'afgani',
      ALL: 'lek',
      AMD: 'dram',
      ANG: 'florín de las Antillas Neerlandesas',
      AOA: 'kuanza',
      ARS: 'peso argentino',
      AUD: 'dólar australiano',
      AWG: 'florín arubeño',
      AZN: 'manat azerbaiyano',
      BAM: 'marco convertible de Bosnia y Herzegovina',
      BBD: 'dólar barbadense',
      BDT: 'taka',
      BGN: 'lev búlgaro',
      BHD: 'dinar bahreiní',
      BIF: 'franco burundés',
      BMD: 'dólar de Bermudas',
      BND: 'dólar bruneano',
      BOB: 'boliviano',
      BRL: 'real brasileño',
      BSD: 'dólar bahameño',
      BTN: 'gultrum',
      BWP: 'pula',
      BYN: 'rublo bielorruso',
      BZD: 'dólar beliceño',
      CAD: 'dólar canadiense',
      CDF: 'franco congoleño',
      CHF: 'franco suizo',
      CLP: 'peso chileno',
      CNY: 'yuan',
      COP: 'peso colombiano',
      CRC: 'colón costarricense',
      CUC: 'peso cubano convertible',
      CUP: 'peso cubano',
      CVE: 'escudo de Cabo Verde',
      CZK: 'corona checa',
      DJF: 'franco yibutiano',
      DKK: 'corona danesa',
      DOP: 'peso dominicano',
      DZD: 'dinar argelino',
      EGP: 'libra egipcia',
      ERN: 'nakfa',
      ETB: 'bir',
      EUR: 'euro',
      FJD: 'dólar fiyiano',
      FKP: 'libra malvinense',
      GBP: 'libra esterlina',
      GEL: 'lari',
      GHS: 'cedi',
      GIP: 'libra gibraltareña',
      GMD: 'dalasi',
      GNF: 'franco guineano',
      GTQ: 'quetzal guatemalteco',
      GYD: 'dólar guyanés',
      HKD: 'dólar hongkonés',
      HNL: 'lempira hondureño',
      HRK: 'kuna',
      HTG: 'gourde haitiano',
      HUF: 'forinto húngaro',
      IDR: 'rupia indonesia',
      ILS: 'nuevo séquel israelí',
      INR: 'rupia india',
      IQD: 'dinar iraquí',
      IRR: 'rial iraní',
      ISK: 'corona islandesa',
      JMD: 'dólar jamaicano',
      JOD: 'dinar jordano',
      JPY: 'yen',
      KES: 'chelín keniano',
      KGS: 'som',
      KHR: 'riel',
      KMF: 'franco comorense',
      KPW: 'won norcoreano',
      KRW: 'won surcoreano',
      KWD: 'dinar kuwaití',
      KYD: 'dólar de las Islas Caimán',
      KZT: 'tenge kazako',
      LAK: 'kip',
      LBP: 'libra libanesa',
      LKR: 'rupia esrilanquesa',
      LRD: 'dólar liberiano',
      LSL: 'loti lesothense',
      LYD: 'dinar libio',
      MAD: 'dírham marroquí',
      MDL: 'leu moldavo',
      MGA: 'ariari',
      MKD: 'dinar macedonio',
      MMK: 'kiat',
      MNT: 'tugrik',
      MOP: 'pataca de Macao',
      MRU: 'uguiya',
      MUR: 'rupia mauriciana',
      MVR: 'rufiya',
      MWK: 'kuacha malauí',
      MXN: 'peso mexicano',
      MYR: 'ringit',
      MZN: 'metical',
      NAD: 'dólar namibio',
      NGN: 'naira',
      NIO: 'córdoba nicaragüense',
      NOK: 'corona noruega',
      NPR: 'rupia nepalí',
      NZD: 'dólar neozelandés',
      OMR: 'rial omaní',
      PAB: 'balboa panameño',
      PEN: 'sol peruano',
      PGK: 'kina',
      PHP: 'peso filipino',
      PKR: 'rupia pakistaní',
      PLN: 'esloti',
      PYG: 'guaraní paraguayo',
      QAR: 'rial catarí',
      RON: 'leu rumano',
      RSD: 'dinar serbio',
      RUB: 'rublo ruso',
      RWF: 'franco ruandés',
      SAR: 'rial saudí',
      SBD: 'dólar salomonense',
      SCR: 'rupia seychellense',
      SDG: 'libra sudanesa',
      SEK: 'corona sueca',
      SGD: 'dólar singapurense',
      SHP: 'libra de Santa Elena',
      SLL: 'leona',
      SOS: 'chelín somalí',
      SRD: 'dólar surinamés',
      STN: 'dobra',
      SVC: 'colón salvadoreño',
      SYP: 'libra siria',
      SZL: 'lilangeni',
      THB: 'bat',
      TJS: 'somoni tayiko',
      TMT: 'manat turcomano',
      TND: 'dinar tunecino',
      TOP: 'paanga',
      TRY: 'lira turca',
      TTD: 'dólar de Trinidad y Tobago',
      TWD: 'nuevo dólar taiwanés',
      TZS: 'chelín tanzano',
      UAH: 'grivna',
      UGX: 'chelín ugandés',
      USD: 'dólar estadounidense',
      UYU: 'peso uruguayo',
      UZS: 'sum',
      VND: 'dong',
      VUV: 'vatu',
      WST: 'tala',
      XAF: 'franco CFA de África Central',
      XCD: 'dólar del Caribe Oriental',
      XDR: 'derechos especiales de giro',
      XOF: 'franco CFA de África Occidental',
      XPF: 'franco CFP',
      XXX: 'moneda desconocida',
      YER: 'rial yemení',
      ZAR: 'rand',
      ZMW: 'kuacha zambiano',
    },
    pp: '#,##0 %',
    cp: '#,##0.00 ¤',
    ap: '#,##0.00 ¤',
  },
  root
);

// Common Locale Parents
export const es_419 = new Locale(
  'es_419',
  {
    cs: {},
    cn: { MWK: 'kwacha malauí', THB: 'baht tailandes', UZS: 'som uzbeko' },
    cp: '¤#,##0.00',
    ap: '¤#,##0.00',
  },
  es
);

// Locale Data
export const es_AR = new Locale(
  'es_AR',
  { c: 'ARS', cs: { ARS: '$' }, cn: {}, ap: '¤ #,##0.00;(¤ #,##0.00)' },
  es_419
);
export const es_BO = new Locale(
  'es_BO',
  { c: 'BOB', cs: { BOB: 'Bs' }, cn: {} },
  es_419
);
export const es_BR = new Locale('es_BR', { c: 'BRL', cs: {}, cn: {} }, es_419);
export const es_BZ = new Locale(
  'es_BZ',
  { c: 'BZD', cs: { BZD: '$' }, cn: {} },
  es_419
);
export const es_CL = new Locale(
  'es_CL',
  {
    c: 'CLP',
    cs: { CLP: '$' },
    cn: { CLP: 'Peso chileno' },
    cp: '¤#,##0.00;¤-#,##0.00',
  },
  es_419
);
export const es_CO = new Locale(
  'es_CO',
  { c: 'COP', cs: { COP: '$' }, cn: {} },
  es_419
);
export const es_CR = new Locale(
  'es_CR',
  { g: ' ', c: 'CRC', cs: { CRC: '₡' }, cn: {} },
  es_419
);
export const es_CU = new Locale(
  'es_CU',
  { c: 'CUC', cs: { CUP: '$' }, cn: {} },
  es_419
);
export const es_DO = new Locale(
  'es_DO',
  { c: 'DOP', cs: { DOP: 'RD$' }, cn: {}, ap: '¤#,##0.00;(¤#,##0.00)' },
  es_419
);
export const es_EA = new Locale('es_EA', { c: 'EUR', cs: {}, cn: {} }, es);
export const es_EC = new Locale(
  'es_EC',
  { c: 'USD', cs: { USD: '$' }, cn: {}, cp: '¤#,##0.00;¤-#,##0.00' },
  es_419
);
export const es_GQ = new Locale(
  'es_GQ',
  { c: 'XAF', cs: {}, cn: {}, cp: '¤#,##0.00' },
  es
);
export const es_GT = new Locale(
  'es_GT',
  { c: 'GTQ', cs: { GTQ: 'Q' }, cn: { GTQ: 'quetzal' } },
  es_419
);
export const es_HN = new Locale(
  'es_HN',
  { c: 'HNL', cs: { HNL: 'L' }, cn: {} },
  es_419
);
export const es_IC = new Locale('es_IC', { c: 'EUR', cs: {}, cn: {} }, es);
export const es_MX = new Locale(
  'es_MX',
  {
    c: 'MXN',
    cs: { MRU: 'UM', MXN: '$' },
    cn: {
      BDT: 'taka bangladesí',
      BTN: 'ngultrum butanés',
      KGS: 'som kirguís',
      KHR: 'riel camboyano',
      LAK: 'kip laosiano',
      MVR: 'rupia de Maldivas',
      STN: 'dobra santotomense',
      THB: 'baht tailandés',
      VND: 'dong vietnamita',
      ZMW: 'kwacha zambiano',
    },
  },
  es_419
);
export const es_NI = new Locale(
  'es_NI',
  { c: 'NIO', cs: { NIO: 'C$' }, cn: {} },
  es_419
);
export const es_PA = new Locale(
  'es_PA',
  { c: 'USD', cs: { PAB: 'B/.' }, cn: {} },
  es_419
);
export const es_PE = new Locale(
  'es_PE',
  { c: 'PEN', cs: { PEN: 'S/' }, cn: {} },
  es_419
);
export const es_PH = new Locale(
  'es_PH',
  { c: 'PHP', cs: { PHP: '₱' }, cn: {} },
  es
);
export const es_PR = new Locale(
  'es_PR',
  { c: 'USD', cs: { USD: '$' }, cn: {} },
  es_419
);
export const es_PY = new Locale(
  'es_PY',
  { c: 'PYG', cs: { PYG: 'Gs.' }, cn: {}, cp: '¤ #,##0.00;¤ -#,##0.00' },
  es_419
);
export const es_SV = new Locale(
  'es_SV',
  { c: 'USD', cs: { USD: '$' }, cn: {} },
  es_419
);
export const es_US = new Locale(
  'es_US',
  {
    c: 'USD',
    cs: { JPY: '¥', USD: '$' },
    cn: {
      BDT: 'taka bangladesí',
      BTN: 'ngultrum butanés',
      KGS: 'som kirguís',
      LAK: 'kip laosiano',
      STN: 'dobra santotomense',
      VND: 'dong vietnamita',
      XAF: 'franco CFA de África central',
      ZMW: 'kwacha zambiano',
    },
  },
  es_419
);
export const es_UY = new Locale(
  'es_UY',
  { c: 'UYU', cs: { UYU: '$' }, cn: {}, ap: '¤ #,##0.00;(¤ #,##0.00)' },
  es_419
);
export const es_VE = new Locale(
  'es_VE',
  { c: 'VES', cs: {}, cn: {}, cp: '¤#,##0.00;¤-#,##0.00' },
  es_419
);

// Default Export
export default es;
