/* Automatically generated by gen_l10n_data.py */
import { Locale } from '../locale';
import root from '../root';

// Unicode CLDR Version 37, retrieved 2020-10-11
export const fr = new Locale(
  'fr',
  {
    d: ',',
    g: ' ',
    cs: {
      ARS: '$AR',
      AUD: '$AU',
      BMD: '$BM',
      BND: '$BN',
      BZD: '$BZ',
      CAD: '$CA',
      CLP: '$CL',
      COP: '$CO',
      FJD: '$FJ',
      FKP: '£FK',
      GBP: '£GB',
      GIP: '£GI',
      LBP: '£LB',
      MXN: '$MX',
      NAD: '$NA',
      NZD: '$NZ',
      SBD: '$SB',
      SGD: '$SG',
      SRD: '$SR',
      TTD: '$TT',
      USD: '$US',
      UYU: '$UY',
      WST: '$WS',
      XPF: 'FCFP',
    },
    cn: {
      AED: 'dirham des Émirats arabes unis',
      AFN: 'afghani afghan',
      ALL: 'lek albanais',
      AMD: 'dram arménien',
      ANG: 'florin antillais',
      AOA: 'kwanza angolais',
      ARS: 'peso argentin',
      AUD: 'dollar australien',
      AWG: 'florin arubais',
      AZN: 'manat azéri',
      BAM: 'mark convertible bosniaque',
      BBD: 'dollar barbadien',
      BDT: 'taka bangladeshi',
      BGN: 'lev bulgare',
      BHD: 'dinar bahreïni',
      BIF: 'franc burundais',
      BMD: 'dollar bermudien',
      BND: 'dollar brunéien',
      BOB: 'boliviano bolivien',
      BRL: 'réal brésilien',
      BSD: 'dollar bahaméen',
      BTN: 'ngultrum bouthanais',
      BWP: 'pula botswanais',
      BYN: 'rouble biélorusse',
      BZD: 'dollar bélizéen',
      CAD: 'dollar canadien',
      CDF: 'franc congolais',
      CHF: 'franc suisse',
      CLP: 'peso chilien',
      CNY: 'yuan renminbi chinois',
      COP: 'peso colombien',
      CRC: 'colón costaricain',
      CUC: 'peso cubain convertible',
      CUP: 'peso cubain',
      CVE: 'escudo capverdien',
      CZK: 'couronne tchèque',
      DJF: 'franc djiboutien',
      DKK: 'couronne danoise',
      DOP: 'peso dominicain',
      DZD: 'dinar algérien',
      EGP: 'livre égyptienne',
      ERN: 'nafka érythréen',
      ETB: 'birr éthiopien',
      EUR: 'euro',
      FJD: 'dollar fidjien',
      FKP: 'livre des îles Malouines',
      GBP: 'livre sterling',
      GEL: 'lari géorgien',
      GHS: 'cédi ghanéen',
      GIP: 'livre de Gibraltar',
      GMD: 'dalasi gambien',
      GNF: 'franc guinéen',
      GTQ: 'quetzal guatémaltèque',
      GYD: 'dollar du Guyana',
      HKD: 'dollar de Hong Kong',
      HNL: 'lempira hondurien',
      HRK: 'kuna croate',
      HTG: 'gourde haïtienne',
      HUF: 'forint hongrois',
      IDR: 'roupie indonésienne',
      ILS: 'nouveau shekel israélien',
      INR: 'roupie indienne',
      IQD: 'dinar irakien',
      IRR: 'riyal iranien',
      ISK: 'couronne islandaise',
      JMD: 'dollar jamaïcain',
      JOD: 'dinar jordanien',
      JPY: 'yen japonais',
      KES: 'shilling kényan',
      KGS: 'som kirghize',
      KHR: 'riel cambodgien',
      KMF: 'franc comorien',
      KPW: 'won nord-coréen',
      KRW: 'won sud-coréen',
      KWD: 'dinar koweïtien',
      KYD: 'dollar des îles Caïmans',
      KZT: 'tenge kazakh',
      LAK: 'kip loatien',
      LBP: 'livre libanaise',
      LKR: 'roupie srilankaise',
      LRD: 'dollar libérien',
      LSL: 'loti lesothan',
      LYD: 'dinar libyen',
      MAD: 'dirham marocain',
      MDL: 'leu moldave',
      MGA: 'ariary malgache',
      MKD: 'denar macédonien',
      MMK: 'kyat myanmarais',
      MNT: 'tugrik mongol',
      MOP: 'pataca macanaise',
      MRU: 'ouguiya mauritanien',
      MUR: 'roupie mauricienne',
      MVR: 'rufiyaa maldivien',
      MWK: 'kwacha malawite',
      MXN: 'peso mexicain',
      MYR: 'ringgit malais',
      MZN: 'metical mozambicain',
      NAD: 'dollar namibien',
      NGN: 'naira nigérian',
      NIO: 'córdoba oro nicaraguayen',
      NOK: 'couronne norvégienne',
      NPR: 'roupie népalaise',
      NZD: 'dollar néo-zélandais',
      OMR: 'riyal omanais',
      PAB: 'balboa panaméen',
      PEN: 'sol péruvien',
      PGK: 'kina papouan-néo-guinéen',
      PHP: 'peso philippin',
      PKR: 'roupie pakistanaise',
      PLN: 'zloty polonais',
      PYG: 'guaraní paraguayen',
      QAR: 'riyal qatari',
      RON: 'leu roumain',
      RSD: 'dinar serbe',
      RUB: 'rouble russe',
      RWF: 'franc rwandais',
      SAR: 'riyal saoudien',
      SBD: 'dollar des îles Salomon',
      SCR: 'roupie des Seychelles',
      SDG: 'livre soudanaise',
      SEK: 'couronne suédoise',
      SGD: 'dollar de Singapour',
      SHP: 'livre de Sainte-Hélène',
      SLL: 'leone sierra-léonais',
      SOS: 'shilling somalien',
      SRD: 'dollar surinamais',
      STN: 'dobra santoméen',
      SVC: 'colón salvadorien',
      SYP: 'livre syrienne',
      SZL: 'lilangeni swazi',
      THB: 'baht thaïlandais',
      TJS: 'somoni tadjik',
      TMT: 'nouveau manat turkmène',
      TND: 'dinar tunisien',
      TOP: 'pa’anga tongan',
      TRY: 'livre turque',
      TTD: 'dollar trinidadien',
      TWD: 'nouveau dollar taïwanais',
      TZS: 'shilling tanzanien',
      UAH: 'hryvnia ukrainienne',
      UGX: 'shilling ougandais',
      USD: 'dollar des États-Unis',
      UYU: 'peso uruguayen',
      UZS: 'sum ouzbek',
      VND: 'dông vietnamien',
      VUV: 'vatu vanuatuan',
      WST: 'tala samoan',
      XAF: 'franc CFA (BEAC)',
      XCD: 'dollar des Caraïbes orientales',
      XDR: 'droit de tirage spécial',
      XOF: 'franc CFA (BCEAO)',
      XPF: 'franc CFP',
      XXX: 'devise inconnue ou non valide',
      YER: 'riyal yéménite',
      ZAR: 'rand sud-africain',
      ZMW: 'kwacha zambien',
    },
    pp: '#,##0 %',
    cp: '#,##0.00 ¤',
    ap: '#,##0.00 ¤;(#,##0.00 ¤)',
  },
  root
);

// Common Locale Parents
// Locale Data
export const fr_BE = new Locale('fr_BE', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_BF = new Locale('fr_BF', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_BI = new Locale(
  'fr_BI',
  { c: 'BIF', cs: { BIF: 'FBu' }, cn: {} },
  fr
);
export const fr_BJ = new Locale('fr_BJ', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_BL = new Locale('fr_BL', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_CA = new Locale(
  'fr_CA',
  {
    g: ' ',
    c: 'CAD',
    cs: {
      AUD: '$ AU',
      CAD: '$',
      HKD: '$ HK',
      JPY: '¥',
      NZD: '$ NZ',
      SGD: '$ SG',
      USD: '$ US',
    },
    cn: {
      AZN: 'manat azerbaïdjanais',
      CVE: 'escudo cap-verdien',
      FKP: 'livre des Îles Malouines',
      IRR: 'rial iranien',
      LAK: 'kip laotien',
      OMR: 'rial omanais',
      PEN: 'nouveau sol péruvien',
      PGK: 'kina papou-néo-guinéen',
      QAR: 'riyal du Qatar',
      SAR: 'rial saoudien',
      SRD: 'dollar du Suriname',
      TOP: 'pa’anga',
      TTD: 'dollar de Trinité-et-Tobago',
      VUV: 'vatu',
      WST: 'tala',
      XXX: 'Devise inconnue',
      YER: 'rial yéménite',
    },
  },
  fr
);
export const fr_CD = new Locale(
  'fr_CD',
  { c: 'CDF', cs: { CDF: 'FC' }, cn: {} },
  fr
);
export const fr_CF = new Locale('fr_CF', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_CG = new Locale('fr_CG', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_CH = new Locale('fr_CH', { c: 'CHF', cs: {}, cn: {} }, fr);
export const fr_CI = new Locale('fr_CI', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_CM = new Locale('fr_CM', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_DJ = new Locale(
  'fr_DJ',
  { c: 'DJF', cs: { DJF: 'Fdj' }, cn: {} },
  fr
);
export const fr_DZ = new Locale(
  'fr_DZ',
  { c: 'DZD', cs: { DZD: 'DA' }, cn: {} },
  fr
);
export const fr_GA = new Locale('fr_GA', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_GF = new Locale('fr_GF', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_GN = new Locale(
  'fr_GN',
  { c: 'GNF', cs: { GNF: 'FG' }, cn: {} },
  fr
);
export const fr_GP = new Locale('fr_GP', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_GQ = new Locale('fr_GQ', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_HT = new Locale(
  'fr_HT',
  { c: 'USD', cs: { HTG: 'G' }, cn: {} },
  fr
);
export const fr_KM = new Locale(
  'fr_KM',
  { c: 'KMF', cs: { KMF: 'CF' }, cn: {} },
  fr
);
export const fr_LU = new Locale(
  'fr_LU',
  { g: '.', c: 'EUR', cs: {}, cn: {} },
  fr
);
export const fr_MA = new Locale(
  'fr_MA',
  { g: '.', c: 'MAD', cs: {}, cn: {} },
  fr
);
export const fr_MC = new Locale('fr_MC', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_MF = new Locale('fr_MF', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_MG = new Locale(
  'fr_MG',
  { c: 'MGA', cs: { MGA: 'Ar' }, cn: {} },
  fr
);
export const fr_ML = new Locale('fr_ML', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_MQ = new Locale('fr_MQ', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_MR = new Locale(
  'fr_MR',
  { c: 'MRU', cs: { MRU: 'UM' }, cn: {} },
  fr
);
export const fr_MU = new Locale(
  'fr_MU',
  { c: 'MUR', cs: { MUR: 'Rs' }, cn: {} },
  fr
);
export const fr_NC = new Locale('fr_NC', { c: 'XPF', cs: {}, cn: {} }, fr);
export const fr_NE = new Locale('fr_NE', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_PF = new Locale('fr_PF', { c: 'XPF', cs: {}, cn: {} }, fr);
export const fr_PM = new Locale('fr_PM', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_RE = new Locale('fr_RE', { c: 'EUR', cs: {}, cn: {} }, fr);
export const fr_RW = new Locale(
  'fr_RW',
  { c: 'RWF', cs: { RWF: 'RF' }, cn: {} },
  fr
);
export const fr_SC = new Locale(
  'fr_SC',
  { c: 'SCR', cs: { SCR: 'SR' }, cn: {} },
  fr
);
export const fr_SN = new Locale('fr_SN', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_SY = new Locale(
  'fr_SY',
  { c: 'SYP', cs: { SYP: 'LS' }, cn: {} },
  fr
);
export const fr_TD = new Locale('fr_TD', { c: 'XAF', cs: {}, cn: {} }, fr);
export const fr_TG = new Locale('fr_TG', { c: 'XOF', cs: {}, cn: {} }, fr);
export const fr_TN = new Locale(
  'fr_TN',
  { c: 'TND', cs: { TND: 'DT' }, cn: {} },
  fr
);
export const fr_VU = new Locale(
  'fr_VU',
  { c: 'VUV', cs: { VUV: 'VT' }, cn: {} },
  fr
);
export const fr_WF = new Locale('fr_WF', { c: 'XPF', cs: {}, cn: {} }, fr);
export const fr_YT = new Locale('fr_YT', { c: 'EUR', cs: {}, cn: {} }, fr);

// Default Export
export default fr;
