/**
 * Automatically generated by gen_l10n_data.py
 * @packageDocumentation
 * @internal
 */
import { Locale } from '../locale';

// Unicode CLDR Version 37, retrieved 2020-10-13
export default new Locale('root', {
  d: '.',
  g: ',',
  p: '+',
  m: '-',
  pc: '%',
  pm: '‰',
  e: 'E',
  x: '×',
  inf: '∞',
  nan: 'NaN',
  cs: {
    AUD: 'A$',
    BRL: 'R$',
    CAD: 'CA$',
    CNY: 'CN¥',
    EUR: '€',
    GBP: '£',
    HKD: 'HK$',
    ILS: '₪',
    INR: '₹',
    JPY: 'JP¥',
    KRW: '₩',
    MXN: 'MX$',
    NZD: 'NZ$',
    TWD: 'NT$',
    USD: 'US$',
    VND: '₫',
    XAF: 'FCFA',
    XCD: 'EC$',
    XOF: 'CFA',
    XPF: 'CFPF',
    XXX: '¤',
  },
  cn: {},
  np: '#,##0.###',
  pp: '#,##0%',
  sp: '#E0',
  cp: '¤ #,##0.00',
  ap: '¤ #,##0.00',
});
